from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = ROOT / "track-a-regularity/reports/lemma_0252_proof_obligation_graph.json"
DEFAULT_MARKDOWN_OUTPUT = ROOT / "track-a-regularity/reports/proof_obligation_blocker_summary.md"
DEFAULT_JSON_OUTPUT = ROOT / "track-a-regularity/reports/proof_obligation_blocker_summary.json"


class BlockerReportError(ValueError):
    pass


@dataclass(frozen=True)
class BlockerSummary:
    lemma_id: str
    candidate_status: str
    active_candidate: bool
    node_count: int
    promotion_blocker_count: int
    promotion_blocker_keys: tuple[str, ...]

    @property
    def has_active_candidate_blocker_conflict(self) -> bool:
        return self.active_candidate and self.promotion_blocker_count > 0


def _require_mapping(data: object, label: str) -> dict[str, Any]:
    if not isinstance(data, dict):
        raise BlockerReportError(f"{label} must be a JSON object")
    return data


def _require_string(data: dict[str, Any], key: str) -> str:
    value = data.get(key)
    if not isinstance(value, str):
        raise BlockerReportError(f"{key} must be a string")
    return value


def _require_bool(data: dict[str, Any], key: str) -> bool:
    value = data.get(key)
    if not isinstance(value, bool):
        raise BlockerReportError(f"{key} must be a boolean")
    return value


def _require_list(data: dict[str, Any], key: str) -> list[Any]:
    value = data.get(key)
    if not isinstance(value, list):
        raise BlockerReportError(f"{key} must be a list")
    return value


def load_blocker_summary(path: Path) -> BlockerSummary:
    try:
        data = _require_mapping(json.loads(path.read_text(encoding="utf-8")), "report")
    except FileNotFoundError as exc:
        raise BlockerReportError(f"missing proof-obligation JSON: {path}") from exc
    except json.JSONDecodeError as exc:
        raise BlockerReportError(f"invalid proof-obligation JSON: {path}: {exc}") from exc

    if data.get("schema_version") != 1:
        raise BlockerReportError("schema_version must be 1")

    nodes = _require_list(data, "nodes")
    promotion_blockers = _require_list(data, "promotion_blockers")
    blocker_keys: list[str] = []
    for index, blocker in enumerate(promotion_blockers):
        blocker_data = _require_mapping(blocker, f"promotion_blockers[{index}]")
        blocker_keys.append(_require_string(blocker_data, "key"))

    return BlockerSummary(
        lemma_id=_require_string(data, "lemma_id"),
        candidate_status=_require_string(data, "candidate_status"),
        active_candidate=_require_bool(data, "active_candidate"),
        node_count=len(nodes),
        promotion_blocker_count=len(promotion_blockers),
        promotion_blocker_keys=tuple(blocker_keys),
    )


def summary_to_dict(summary: BlockerSummary) -> dict[str, object]:
    return {
        "lemma_id": summary.lemma_id,
        "candidate_status": summary.candidate_status,
        "active_candidate": summary.active_candidate,
        "node_count": summary.node_count,
        "promotion_blocker_count": summary.promotion_blocker_count,
        "promotion_blocker_keys": list(summary.promotion_blocker_keys),
        "active_candidate_blocker_conflict": summary.has_active_candidate_blocker_conflict,
    }


def render_summary(summary: BlockerSummary) -> str:
    blocker_keys = ", ".join(summary.promotion_blocker_keys) or "none"
    conflict = str(summary.has_active_candidate_blocker_conflict).lower()
    return "\n".join(
        (
            f"lemma_id: {summary.lemma_id}",
            f"candidate_status: {summary.candidate_status}",
            f"active_candidate: {str(summary.active_candidate).lower()}",
            f"node_count: {summary.node_count}",
            f"promotion_blocker_count: {summary.promotion_blocker_count}",
            f"promotion_blocker_keys: {blocker_keys}",
            f"active_candidate_blocker_conflict: {conflict}",
        )
    )


def render_markdown_summary(summary: BlockerSummary) -> str:
    blocker_rows = [
        "| key |",
        "|---|",
        *(f"| `{key}` |" for key in summary.promotion_blocker_keys),
    ]
    if not summary.promotion_blocker_keys:
        blocker_rows.append("| none |")

    return "\n".join(
        (
            "# Proof-Obligation Blocker Summary",
            "",
            "Generated by `track-a-regularity/evaluator/proof_obligation_blockers.py`.",
            "",
            "## Status",
            "",
            f"- lemma_id: `{summary.lemma_id}`",
            f"- candidate_status: `{summary.candidate_status}`",
            f"- active_candidate: `{str(summary.active_candidate).lower()}`",
            f"- node_count: `{summary.node_count}`",
            f"- promotion_blocker_count: `{summary.promotion_blocker_count}`",
            "- active_candidate_blocker_conflict: "
            f"`{str(summary.has_active_candidate_blocker_conflict).lower()}`",
            "",
            "## Promotion Blockers",
            "",
            *blocker_rows,
            "",
            "## Non-Claim",
            "",
            "This summary is a metadata guardrail only. It is not a proof of epsilon regularity,",
            "weak-to-smooth continuation, or Navier-Stokes regularity.",
            "",
        )
    )


def render_json_summary(summary: BlockerSummary) -> str:
    return json.dumps(summary_to_dict(summary), indent=2, sort_keys=True) + "\n"


def render_output(summary: BlockerSummary, output_format: str) -> str:
    if output_format == "text":
        return render_summary(summary) + "\n"
    if output_format == "markdown":
        return render_markdown_summary(summary)
    if output_format == "json":
        return render_json_summary(summary)
    raise ValueError(f"unknown blocker summary format: {output_format}")


def write_summary(output: Path, summary: BlockerSummary, output_format: str) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_output(summary, output_format), encoding="utf-8")
    return output


def check_summary_output(
    output: Path, summary: BlockerSummary, output_format: str
) -> tuple[bool, str]:
    expected = render_output(summary, output_format)
    if not output.exists():
        return False, f"missing blocker summary: {output}"
    current = output.read_text(encoding="utf-8")
    if current != expected:
        return False, f"stale blocker summary: {output}"
    return True, f"fresh blocker summary: {output}"


def check_summary(summary: BlockerSummary) -> tuple[bool, str]:
    if summary.has_active_candidate_blocker_conflict:
        return (
            False,
            "active candidate still has promotion blockers: "
            + ", ".join(summary.promotion_blocker_keys),
        )
    return True, "blocker summary check passed"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Summarize and check a proof-obligation JSON blocker report."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="Proof-obligation JSON report path.",
    )
    parser.add_argument(
        "--format",
        choices=("text", "markdown", "json"),
        default="text",
        help="Summary output format.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional output path for a rendered summary.",
    )
    parser.add_argument(
        "--check-output",
        action="store_true",
        help="Check that --output already matches the rendered summary.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if an active candidate still has promotion blockers.",
    )
    args = parser.parse_args(argv)

    try:
        summary = load_blocker_summary(args.input)
    except BlockerReportError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    if args.output is not None:
        if args.check_output:
            ok, message = check_summary_output(args.output, summary, args.format)
            print(message)
            if not ok:
                print("run without --check-output to regenerate the summary", file=sys.stderr)
                return 1
        else:
            output = write_summary(args.output, summary, args.format)
            print(f"wrote {output}")
    elif args.check_output:
        print("--check-output requires --output", file=sys.stderr)
        return 1
    else:
        print(render_output(summary, args.format), end="")

    if args.check:
        ok, message = check_summary(summary)
        print(message)
        if not ok:
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
