from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MARKDOWN_OUTPUT = ROOT / "track-a-regularity/reports/lemma_0252_proof_obligation_graph.md"
DEFAULT_JSON_OUTPUT = ROOT / "track-a-regularity/reports/lemma_0252_proof_obligation_graph.json"
DEFAULT_OUTPUT = DEFAULT_MARKDOWN_OUTPUT


@dataclass(frozen=True)
class ObligationNode:
    key: str
    label: str
    status: str
    supplied_as_assumption: bool
    proved_in_current_artifact: bool
    blocker: str


@dataclass(frozen=True)
class Lemma0252GraphReport:
    lemma_id: str
    candidate_status: str
    active_candidate: bool
    lean_artifact: str
    graph_doc: str
    formal_map_doc: str
    nodes: tuple[ObligationNode, ...]

    @property
    def blocking_nodes(self) -> tuple[ObligationNode, ...]:
        return tuple(
            node
            for node in self.nodes
            if node.status in {"missing_mechanism", "guardrail_only"}
            and not node.proved_in_current_artifact
        )


def lemma_0252_graph_report() -> Lemma0252GraphReport:
    return Lemma0252GraphReport(
        lemma_id="lemma_0252",
        candidate_status="needs_review",
        active_candidate=False,
        lean_artifact="track-c-formal/lean/NavierStokesProgram/ProofObligationGraph.lean",
        graph_doc="docs/STEP64_PROOF_OBLIGATION_GRAPH.md",
        formal_map_doc="docs/LEMMA_0252_LOCAL_ENERGY_FORMAL_MAP.md",
        nodes=(
            ObligationNode(
                key="cylinder_admissibility",
                label="Cylinder admissibility",
                status="partial_vocabulary",
                supplied_as_assumption=True,
                proved_in_current_artifact=False,
                blocker="No theorem that cylinders are admissible inside the terminal time interval.",
            ),
            ObligationNode(
                key="enstrophy_to_local_energy",
                label="Local vorticity to local-energy quantities",
                status="vocabulary_only",
                supplied_as_assumption=True,
                proved_in_current_artifact=False,
                blocker="No curl-to-gradient localization, cutoff-error identity, or local decomposition.",
            ),
            ObligationNode(
                key="pressure_control",
                label="Pressure control",
                status="vocabulary_only",
                supplied_as_assumption=True,
                proved_in_current_artifact=False,
                blocker="No pressure equation, Calderon-Zygmund estimate, or local/nonlocal pressure bound.",
            ),
            ObligationNode(
                key="finite_bound_to_smallness",
                label="Finite bound to epsilon smallness",
                status="missing_mechanism",
                supplied_as_assumption=False,
                proved_in_current_artifact=False,
                blocker="No monotonicity, self-improvement, or finite-critical-mass to smallness route.",
            ),
            ObligationNode(
                key="compactness_liouville",
                label="Compactness and Liouville branch",
                status="missing_mechanism",
                supplied_as_assumption=False,
                proved_in_current_artifact=False,
                blocker="No ancient suitable limit, compactness theorem, or Liouville/backward-uniqueness theorem.",
            ),
            ObligationNode(
                key="smooth_continuation_bridge",
                label="Smooth continuation bridge",
                status="guardrail_only",
                supplied_as_assumption=False,
                proved_in_current_artifact=False,
                blocker="No bridge from local regularity metadata to BKM/Serrin/high-Sobolev continuation.",
            ),
        ),
    )


def render_markdown(report: Lemma0252GraphReport) -> str:
    rows = [
        "| obligation | status | supplied as assumption | proved in artifact | blocker |",
        "|---|---|---:|---:|---|",
    ]
    for node in report.nodes:
        rows.append(
            "| "
            + " | ".join(
                (
                    node.label,
                    f"`{node.status}`",
                    "yes" if node.supplied_as_assumption else "no",
                    "yes" if node.proved_in_current_artifact else "no",
                    node.blocker,
                )
            )
            + " |"
        )

    blockers = "\n".join(f"- `{node.key}`: {node.blocker}" for node in report.blocking_nodes)

    return "\n".join(
        (
            "# Lemma 0252 Proof-Obligation Graph Report",
            "",
            "Generated by `track-a-regularity/evaluator/proof_obligation_report.py`.",
            "",
            "## Status",
            "",
            f"- lemma: `{report.lemma_id}`",
            f"- candidate_status: `{report.candidate_status}`",
            f"- active_candidate: `{str(report.active_candidate).lower()}`",
            f"- Lean artifact: `{report.lean_artifact}`",
            f"- graph doc: `{report.graph_doc}`",
            f"- formal map doc: `{report.formal_map_doc}`",
            "",
            "This report exposes blocker metadata only. It is not a proof of epsilon regularity,",
            "pressure control, compactness, smooth continuation, or Navier-Stokes regularity.",
            "",
            "## Obligation Nodes",
            "",
            *rows,
            "",
            "## Promotion Blockers",
            "",
            blockers,
            "",
        )
    )


def report_to_dict(report: Lemma0252GraphReport) -> dict[str, object]:
    return {
        "schema_version": 1,
        "lemma_id": report.lemma_id,
        "candidate_status": report.candidate_status,
        "active_candidate": report.active_candidate,
        "docs": {
            "lean_artifact": report.lean_artifact,
            "graph_doc": report.graph_doc,
            "formal_map_doc": report.formal_map_doc,
        },
        "nodes": [
            {
                "key": node.key,
                "label": node.label,
                "status": node.status,
                "supplied_as_assumption": node.supplied_as_assumption,
                "proved_in_current_artifact": node.proved_in_current_artifact,
                "blocker": node.blocker,
            }
            for node in report.nodes
        ],
        "promotion_blockers": [
            {
                "key": node.key,
                "status": node.status,
                "blocker": node.blocker,
            }
            for node in report.blocking_nodes
        ],
        "non_claims": [
            "no_navier_stokes_solution",
            "no_epsilon_regularity_theorem",
            "no_pressure_estimate",
            "no_compactness_or_liouville_theorem",
            "no_weak_to_smooth_upgrade",
        ],
    }


def render_json(report: Lemma0252GraphReport) -> str:
    return json.dumps(report_to_dict(report), indent=2, sort_keys=True) + "\n"


def render_report(report: Lemma0252GraphReport, output_format: str) -> str:
    if output_format == "markdown":
        return render_markdown(report)
    if output_format == "json":
        return render_json(report)
    raise ValueError(f"unknown proof-obligation report format: {output_format}")


def write_report(output: Path, output_format: str = "markdown") -> Path:
    report = lemma_0252_graph_report()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_report(report, output_format), encoding="utf-8")
    return output


def check_report(output: Path, output_format: str = "markdown") -> tuple[bool, str]:
    expected = render_report(lemma_0252_graph_report(), output_format)
    if not output.exists():
        return False, f"missing report: {output}"
    current = output.read_text(encoding="utf-8")
    if current != expected:
        return False, f"stale report: {output}"
    return True, f"fresh report: {output}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Emit the lemma_0252 proof-obligation graph report."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path. Defaults to the canonical Markdown or JSON report path.",
    )
    parser.add_argument(
        "--format",
        choices=("markdown", "json"),
        default="markdown",
        help="Report serialization format.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that the output path already matches the rendered report.",
    )
    args = parser.parse_args(argv)
    output = args.output
    if output is None:
        output = DEFAULT_JSON_OUTPUT if args.format == "json" else DEFAULT_MARKDOWN_OUTPUT

    if args.check:
        ok, message = check_report(output, args.format)
        print(message)
        if ok:
            return 0
        print("run without --check to regenerate the report", file=sys.stderr)
        return 1

    output = write_report(output, args.format)
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
